spring:
  application:
    name: Donor Search backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/donor_search_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080
