spring:
  application:
    name: Donor Search backend
  profiles:
    active: "dev"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/donor_search_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
---
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoint:
    health:
      show-details: never
